---
- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Build and start Docker containers
  docker_compose:
    project_src: "{{ carscraper }}"
    restarted: yes
    pull: yes